version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    networks:
      - backend

  go-app:
    build:
      context: ./go-app
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      - timescaledb
    volumes:
      - ./go-app:/app
    working_dir: /app
    command: "air"
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  timescaledb-data:

networks:
  backend:
    driver: bridge
